kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: a-l3
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      name: a
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: a
