kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: b-l3
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      name: b
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: b

