apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: d
    spec:
      containers:
      - name: d
        image: docker.io/nginx:1.15.8
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
      volumes:
        - name: html
          configMap:
            name: response-cluster2
            items:
              - key: message
                path: index.html
