apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L4 policy to restrict application a access to only containers in application a network"
metadata:
  name: "l4-c"
spec:
  endpointSelector:
    matchLabels:
      name: c
  ingress:
  - fromEndpoints:
    - matchLabels:
            name: a
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/test"
