apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: a
    spec:
      containers:
      - name: a
        image: fnature/ngnix-curl:2
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
      volumes:
        - name: html
          configMap:
            name: res-clust1
            items:
              - key: message
                path: index.html
