apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: b
  namespace: default
spec:
  rules:
  - services: ["b-svc.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: a-b
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/a-sa"
  roleRef:
    kind: ServiceRole
    name: b
