apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: d
  namespace: default
spec:
  rules:
  - services: ["d-svc.default.svc.cluster.local","d-svc.default.global"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: all-d
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: d
