apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-app2
spec:
  selector:
    matchLabels:
      app: hello-app2
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-app2
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/node-hello:1.0 
        ports:
        - containerPort: 8080
