apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L4 policy to restrict application a access to only containers in application a network"
metadata:
  name: "l4-b"
spec:
  endpointSelector:
    matchLabels:
      name: b
  ingress:
  - fromEndpoints:
    - matchLabels:
        name: b

