apiVersion: v1
kind: ServiceAccount
metadata:
  name: a-sa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: a
    spec:
      serviceAccountName: a-sa
      containers:
      - name: a
        image: fnature/ngnix-curl:2
        ports:
         - containerPort: 80
           name: http
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: html
          configMap:
            name: res-clust1
            items:
              - key: message
                path: index.html
