apiVersion: v1
kind: ServiceAccount
metadata:
  name: b-sa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: b
    spec:
      serviceAccountName: b-sa
      containers:
      - name: b
        image: fnature/ngnix-curl:1
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
      volumes:
        - name: html
          configMap:
            name: res-clust1
            items:
              - key: message
                path: index.html
