apiVersion: v1
kind: ServiceAccount
metadata:
  name: d-sa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: d
    spec:
      serviceAccountName: d-sa
      containers:
      - name: d
        image: fnature/ngnix-curl:1
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
      volumes:
        - name: html
          configMap:
            name: res-clust2
            items:
              - key: message
                path: index.html
